//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoosterBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoosterBot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for any Conquest mode lobby....
        /// </summary>
        internal static string Conquest_Log_Check_AnyLobby {
            get {
                return ResourceManager.GetString("Conquest_Log_Check_AnyLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for win, loss, or ticket claim screens....
        /// </summary>
        internal static string Conquest_Log_Check_Screens {
            get {
                return ResourceManager.GetString("Conquest_Log_Check_Screens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for available tickets....
        /// </summary>
        internal static string Conquest_Log_Check_Tickets {
            get {
                return ResourceManager.GetString("Conquest_Log_Check_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming deck selection....
        /// </summary>
        internal static string Conquest_Log_ConfirmDeck {
            get {
                return ResourceManager.GetString("Conquest_Log_ConfirmDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest match. Playing match....
        /// </summary>
        internal static string Conquest_Log_DetectedActiveMatch {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedActiveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest lobby selection. Entering lobby at selected tier or lower....
        /// </summary>
        internal static string Conquest_Log_DetectedLobby {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected main menu. Returning to start....
        /// </summary>
        internal static string Conquest_Log_DetectedMain {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected end of Conquest match. Returning to Conquest menu....
        /// </summary>
        internal static string Conquest_Log_DetectedMatchEnd {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest prematch. Starting match....
        /// </summary>
        internal static string Conquest_Log_DetectedPrematch {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedPrematch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected end of round in Conquest match. Moving to next round....
        /// </summary>
        internal static string Conquest_Log_DetectedRoundEnd {
            get {
                return ResourceManager.GetString("Conquest_Log_DetectedRoundEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering lobby for new Conquest match....
        /// </summary>
        internal static string Conquest_Log_EnteringLobby {
            get {
                return ResourceManager.GetString("Conquest_Log_EnteringLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to concede match....
        /// </summary>
        internal static string Conquest_Log_Match_Concede {
            get {
                return ResourceManager.GetString("Conquest_Log_Match_Concede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match timer has exceeded 30 minutes. Attempting to exit match....
        /// </summary>
        internal static string Conquest_Log_Match_MaxTimerReached {
            get {
                return ResourceManager.GetString("Conquest_Log_Match_MaxTimerReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing post match screens....
        /// </summary>
        internal static string Conquest_Log_Match_ProcessingPostMatch {
            get {
                return ResourceManager.GetString("Conquest_Log_Match_ProcessingPostMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded maximum wait time of %VALUE% seconds....
        /// </summary>
        internal static string Conquest_Log_MaxWaitTimeReached {
            get {
                return ResourceManager.GetString("Conquest_Log_MaxWaitTimeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to Conquest menu....
        /// </summary>
        internal static string Conquest_Log_Menu {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claiming ticket....
        /// </summary>
        internal static string Conquest_Log_Menu_ClaimTicket {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_ClaimTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest mode lobby....
        /// </summary>
        internal static string Conquest_Log_Menu_DetectedLobby {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_DetectedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to Game Modes tab....
        /// </summary>
        internal static string Conquest_Log_Menu_GameModes {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_GameModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making sure lobby type is set to specified tier or lower: %VALUE%.
        /// </summary>
        internal static string Conquest_Log_Menu_LobbyChoice {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_LobbyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected main menu. Navigating to Conquest mode....
        /// </summary>
        internal static string Conquest_Log_Menu_Main {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tier: %VALUE%.
        /// </summary>
        internal static string Conquest_Log_Menu_SelectedTier {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_SelectedTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for post match screens....
        /// </summary>
        internal static string Conquest_Log_Menu_WaitingPostMatch {
            get {
                return ResourceManager.GetString("Conquest_Log_Menu_WaitingPostMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest post match screens. Returning to Conquest menu....
        /// </summary>
        internal static string Conquest_Log_PostMatch {
            get {
                return ResourceManager.GetString("Conquest_Log_PostMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Conquest routine....
        /// </summary>
        internal static string Conquest_Log_Start {
            get {
                return ResourceManager.GetString("Conquest_Log_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying lobby entry button exists....
        /// </summary>
        internal static string Conquest_Log_VerifyEntryButton {
            get {
                return ResourceManager.GetString("Conquest_Log_VerifyEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected menu for event game mode. Starting new match....
        /// </summary>
        internal static string Event_Log_DetectedEventMenu {
            get {
                return ResourceManager.GetString("Event_Log_DetectedEventMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected main menu. Navigating to limited-time event mode....
        /// </summary>
        internal static string Event_Log_Menu {
            get {
                return ResourceManager.GetString("Event_Log_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to menu for limited-time event mode....
        /// </summary>
        internal static string Event_Log_Menu_ModeTab {
            get {
                return ResourceManager.GetString("Event_Log_Menu_ModeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting routine for limited-time event mode....
        /// </summary>
        internal static string Event_Log_Start {
            get {
                return ResourceManager.GetString("Event_Log_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Ranked Ladder routine....
        /// </summary>
        internal static string Ladder_Log_Start {
            get {
                return ResourceManager.GetString("Ladder_Log_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting blind reset clicks....
        /// </summary>
        internal static string Log_BlindReset {
            get {
                return ResourceManager.GetString("Log_BlindReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is paused. Press [Ctrl+Alt+P] to resume....
        /// </summary>
        internal static string Log_BotPaused {
            get {
                return ResourceManager.GetString("Log_BotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is resuming....
        /// </summary>
        internal static string Log_BotResuming {
            get {
                return ResourceManager.GetString("Log_BotResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for active match....
        /// </summary>
        internal static string Log_Check_ActiveMatch {
            get {
                return ResourceManager.GetString("Log_Check_ActiveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect active match, trying again in 2 seconds....
        /// </summary>
        internal static string Log_Check_ActiveMatch_Failed {
            get {
                return ResourceManager.GetString("Log_Check_ActiveMatch_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for &apos;Concede&apos; button....
        /// </summary>
        internal static string Log_Check_Concede {
            get {
                return ResourceManager.GetString("Log_Check_Concede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking current energy count....
        /// </summary>
        internal static string Log_Check_EnergyState {
            get {
                return ResourceManager.GetString("Log_Check_EnergyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for end of match....
        /// </summary>
        internal static string Log_Check_MatchEnd {
            get {
                return ResourceManager.GetString("Log_Check_MatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for ongoing matchmaking....
        /// </summary>
        internal static string Log_Check_Matchmaking {
            get {
                return ResourceManager.GetString("Log_Check_Matchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchmaking seems to be hanging. Returning to main menu to re-try....
        /// </summary>
        internal static string Log_Check_Matchmaking_Hanged {
            get {
                return ResourceManager.GetString("Log_Check_Matchmaking_Hanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking current match state....
        /// </summary>
        internal static string Log_Check_MatchState {
            get {
                return ResourceManager.GetString("Log_Check_MatchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for post-match screens....
        /// </summary>
        internal static string Log_Check_PostMatchScreen {
            get {
                return ResourceManager.GetString("Log_Check_PostMatchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for &apos;Retreat&apos; button....
        /// </summary>
        internal static string Log_Check_RetreatButton {
            get {
                return ResourceManager.GetString("Log_Check_RetreatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking current turn state....
        /// </summary>
        internal static string Log_Check_TurnState {
            get {
                return ResourceManager.GetString("Log_Check_TurnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking through to next screen....
        /// </summary>
        internal static string Log_ClickNext {
            get {
                return ResourceManager.GetString("Log_ClickNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected active match. Resuming match play....
        /// </summary>
        internal static string Log_DetectedActiveMatch {
            get {
                return ResourceManager.GetString("Log_DetectedActiveMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected main menu. Starting new match....
        /// </summary>
        internal static string Log_DetectedMainMenu {
            get {
                return ResourceManager.GetString("Log_DetectedMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected match end. Returning to main menu....
        /// </summary>
        internal static string Log_DetectedMatchEnd {
            get {
                return ResourceManager.GetString("Log_DetectedMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected matchmaking....
        /// </summary>
        internal static string Log_DetectedMatchmaking {
            get {
                return ResourceManager.GetString("Log_DetectedMatchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected &apos;Reconnect to Game&apos; button. Resuming match play....
        /// </summary>
        internal static string Log_DetectedReconnect {
            get {
                return ResourceManager.GetString("Log_DetectedReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string Log_Error {
            get {
                return ResourceManager.GetString("Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit shortcut [Ctrl+Alt+Q] detected. Terminating process....
        /// </summary>
        internal static string Log_ExitShortcut {
            get {
                return ResourceManager.GetString("Log_ExitShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect main menu. Trying again in 5 seconds....
        /// </summary>
        internal static string Log_FailedMenuDetection {
            get {
                return ResourceManager.GetString("Log_FailedMenuDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** FATAL ERROR *****.
        /// </summary>
        internal static string Log_FatalError {
            get {
                return ResourceManager.GetString("Log_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts:.
        /// </summary>
        internal static string Log_Info_Shortcuts {
            get {
                return ResourceManager.GetString("Log_Info_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ctrl+Alt+P] Pause/resume bot.
        /// </summary>
        internal static string Log_Info_Shortcuts_Pause {
            get {
                return ResourceManager.GetString("Log_Info_Shortcuts_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ctrl+Alt+Q] Quit bot.
        /// </summary>
        internal static string Log_Info_Shortcuts_Quit {
            get {
                return ResourceManager.GetString("Log_Info_Shortcuts_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mode selection..
        /// </summary>
        internal static string Log_InvalidModeSelection {
            get {
                return ResourceManager.GetString("Log_InvalidModeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Conquest lobby. Resetting menu....
        /// </summary>
        internal static string Log_Ladder_DetectedConquest {
            get {
                return ResourceManager.GetString("Log_Ladder_DetectedConquest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to determine loop entry point....
        /// </summary>
        internal static string Log_LoopEntryPoint {
            get {
                return ResourceManager.GetString("Log_LoopEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is hopelessly lost... :/.
        /// </summary>
        internal static string Log_LostBot {
            get {
                return ResourceManager.GetString("Log_LostBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to main menu and restart bot..
        /// </summary>
        internal static string Log_LostBot_Restart {
            get {
                return ResourceManager.GetString("Log_LostBot_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;End Turn&apos;....
        /// </summary>
        internal static string Log_Match_EndTurn {
            get {
                return ResourceManager.GetString("Log_Match_EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting match....
        /// </summary>
        internal static string Log_Match_Exiting {
            get {
                return ResourceManager.GetString("Log_Match_Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected leftover energy, attempting to play cards again....
        /// </summary>
        internal static string Log_Match_LeftoverEnergy {
            get {
                return ResourceManager.GetString("Log_Match_LeftoverEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match timer has exceeded 15 minutes. Attempting retreat....
        /// </summary>
        internal static string Log_Match_MaxTimeReached {
            get {
                return ResourceManager.GetString("Log_Match_MaxTimeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing match....
        /// </summary>
        internal static string Log_Match_Playing {
            get {
                return ResourceManager.GetString("Log_Match_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to play cards... [Turn count: %VALUE%].
        /// </summary>
        internal static string Log_Match_PlayingCards {
            get {
                return ResourceManager.GetString("Log_Match_PlayingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured turn limit (%VALUE%) reached. Attempting retreat....
        /// </summary>
        internal static string Log_Match_ReachedTurnLimit {
            get {
                return ResourceManager.GetString("Log_Match_ReachedTurnLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to snap....
        /// </summary>
        internal static string Log_Match_Snapping {
            get {
                return ResourceManager.GetString("Log_Match_Snapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining snap decision....
        /// </summary>
        internal static string Log_Match_SnapRoll {
            get {
                return ResourceManager.GetString("Log_Match_SnapRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit:  %VALUE%.
        /// </summary>
        internal static string Log_Match_SnapRoll_Limit {
            get {
                return ResourceManager.GetString("Log_Match_SnapRoll_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: %VALUE%.
        /// </summary>
        internal static string Log_Match_SnapRoll_Result {
            get {
                return ResourceManager.GetString("Log_Match_SnapRoll_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap:   %VALUE%.
        /// </summary>
        internal static string Log_Match_SnapRoll_Snap {
            get {
                return ResourceManager.GetString("Log_Match_SnapRoll_Snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting match loop....
        /// </summary>
        internal static string Log_Match_StartingLoop {
            get {
                return ResourceManager.GetString("Log_Match_StartingLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new match....
        /// </summary>
        internal static string Log_Match_StartNew {
            get {
                return ResourceManager.GetString("Log_Match_StartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for turn to progress....
        /// </summary>
        internal static string Log_Match_WaitingForTurn {
            get {
                return ResourceManager.GetString("Log_Match_WaitingForTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for match start... [Elapsed: %ELAPSED%].
        /// </summary>
        internal static string Log_Matchmaking_Waiting {
            get {
                return ResourceManager.GetString("Log_Matchmaking_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string Log_No {
            get {
                return ResourceManager.GetString("Log_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH SNAP!.
        /// </summary>
        internal static string Log_OhSnap {
            get {
                return ResourceManager.GetString("Log_OhSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause shortcut [Ctrl+Alt+P] detected. Pausing bot....
        /// </summary>
        internal static string Log_PauseShortcut {
            get {
                return ResourceManager.GetString("Log_PauseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume shortcut [Ctrl+Alt+P] detected. Resuming bot....
        /// </summary>
        internal static string Log_ResumeShortcut {
            get {
                return ResourceManager.GetString("Log_ResumeShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string Log_Yes {
            get {
                return ResourceManager.GetString("Log_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        internal static string Menu_ConfirmContinue {
            get {
                return ResourceManager.GetString("Menu_ConfirmContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest tier selected:.
        /// </summary>
        internal static string Menu_ConquestConfirm_HighestTier {
            get {
                return ResourceManager.GetString("Menu_ConquestConfirm_HighestTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no tickets exist, bot will only play Proving Grounds..
        /// </summary>
        internal static string Menu_ConquestConfirm_TicketDefault {
            get {
                return ResourceManager.GetString("Menu_ConquestConfirm_TicketDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL available tickets for lobbies at or below the selected tier will be consumed..
        /// </summary>
        internal static string Menu_ConquestConfirm_TicketWarning {
            get {
                return ResourceManager.GetString("Menu_ConquestConfirm_TicketWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the highest tier of Conquest the bot should farm:.
        /// </summary>
        internal static string Menu_ConquestLobby_Description {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** No gold will be consumed. ***.
        /// </summary>
        internal static string Menu_ConquestLobby_NoticeGold {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_NoticeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot will only farm tiers higher than Proving Grounds if tickets are available..
        /// </summary>
        internal static string Menu_ConquestLobby_NoticeTickets {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_NoticeTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] Proving Grounds (default).
        /// </summary>
        internal static string Menu_ConquestLobby_Option1 {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] Silver.
        /// </summary>
        internal static string Menu_ConquestLobby_Option2 {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [3] Gold.
        /// </summary>
        internal static string Menu_ConquestLobby_Option3 {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [4] Infinity.
        /// </summary>
        internal static string Menu_ConquestLobby_Option4 {
            get {
                return ResourceManager.GetString("Menu_ConquestLobby_Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available game modes:.
        /// </summary>
        internal static string Menu_ModeSelect_Description {
            get {
                return ResourceManager.GetString("Menu_ModeSelect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] Conquest.
        /// </summary>
        internal static string Menu_ModeSelect_Option1 {
            get {
                return ResourceManager.GetString("Menu_ModeSelect_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] Ranked ladder.
        /// </summary>
        internal static string Menu_ModeSelect_Option2 {
            get {
                return ResourceManager.GetString("Menu_ModeSelect_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [3] Limited-time event mode.
        /// </summary>
        internal static string Menu_ModeSelect_Option3 {
            get {
                return ResourceManager.GetString("Menu_ModeSelect_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] Yes.
        /// </summary>
        internal static string Menu_Option1_Yes {
            get {
                return ResourceManager.GetString("Menu_Option1_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] No.
        /// </summary>
        internal static string Menu_Option2_No {
            get {
                return ResourceManager.GetString("Menu_Option2_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        internal static string Menu_PressKeyToExit {
            get {
                return ResourceManager.GetString("Menu_PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how many turns to complete before retreating:.
        /// </summary>
        internal static string Menu_RetreatSelect_Description {
            get {
                return ResourceManager.GetString("Menu_RetreatSelect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0] Do not retreat.
        /// </summary>
        internal static string Menu_RetreatSelect_NoRetreat {
            get {
                return ResourceManager.GetString("Menu_RetreatSelect_NoRetreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for selection....
        /// </summary>
        internal static string Menu_WaitingForSelection {
            get {
                return ResourceManager.GetString("Menu_WaitingForSelection", resourceCulture);
            }
        }
    }
}
